using DtsGenerator.TypeScript;
using DtsGenerator.Utilities;
using System;
using System.Collections.Generic;
using System.Text;

namespace DtsGenerator.Generators
{
    public class ModelGenerator : GeneratorBase
    {
        private bool IsSupportBaseClass(TypeScriptClassModel classModel)
        {
            if (string.IsNullOrEmpty(classModel.BaseClass))
                return false;

            // typescript has no Object type
            if (classModel.BaseClass == "Object")
                return false;

            return true;
        }

        public string GenerateClassData(TypeScriptClassModel classModel)
        {
            var sb = new StringBuilder();

            var typeGenerator = new TypeGenerator();

            // class declaration
            sb.AppendLine("export interface "
                + classModel.Name
                + (classModel.IsGeneric ? $"<{GenerateTypeParameters(classModel.TypeParameters)}>" : "")
                + (this.IsSupportBaseClass(classModel) ? " extends " + classModel.BaseClass : "")
                + " {");

            // properties
            foreach (var property in classModel.Properties)
            {
                var emittedType = typeGenerator.GetEmittedType(property.Type);

                sb.AppendLine("\t"                                  // indentation
                    + NameCaseConverter.ToCamelCase(property.Name)  // property name
                    + (property.IsOptional ? "?" : "")              // optional?
                    + ": "
                    + emittedType                                   // property type
                    + ";");
            }

            sb.AppendLine("}");

            return sb.ToString();
        }

        public string GenerateEnumData(TypeScriptEnumModel enumModel)
        {
            var sb = new StringBuilder();

            // enum declaration
            //sb.AppendLine("export enum " + enumModel.Name + " {");
            // const
            sb.AppendLine("const enum " + enumModel.Name + " {");

            // members
            for (int i = 0; i < enumModel.Members.Count; i++)
            {
                var member = enumModel.Members[i];

                sb.AppendLine("\t"                                              // indentation
                    + member.Name                                               // member name
                    + (member.Value.HasValue ? $" = {member.Value.Value}" : "") // optional constant value
                    + (i == enumModel.Members.Count - 1 ? "" : ","));           // skip comma if last value
            }

            sb.AppendLine("}");

            return sb.ToString();
        }

        public string GenerateClass(TypeScriptClassModel classModel, bool includeHeader = true)
        {
            var sb = new StringBuilder();

            if (includeHeader)
            {
                sb.Append(AutogeneratedHeader_Compact());
            }

            // TODO egret项目暂时不要用import，并且加上module
            // imports
            GenerateImportDeclarations(classModel.Imports, sb);

            //data
            sb.AppendLine(this.GenerateClassData(classModel));

            return sb.ToString();
        }

        public string GenerateEnum(TypeScriptEnumModel enumModel, bool includeHeader = true)
        {
            var sb = new StringBuilder();

            if (includeHeader)
            {
                sb.Append(AutogeneratedHeader_Compact());
            }

            // enums have no imports
            //sb.AppendLine("declare module server {");

            //data
            sb.AppendLine(this.GenerateEnumData(enumModel));

            return sb.ToString();
        }
    }
}
