
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.11.0.0
//   Input filename:  C:\Item\youigame\trunk\tools\DtsGenerator\bond\data.bond
//   Output filename: data_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Game.Models
{
    using System.Collections.Generic;

    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.0")]
    public enum EnumItemType
    {
        TypeNone,
        Type1,
        Type2,
        Type3,
        Type4,
        Type5,
        Type6,
        Type7,
        Max,
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.0")]
    public partial class DataItem
    {
        [global::Bond.Id(0)]
        public int id { get; set; }

        [global::Bond.Id(1)]
        public string title { get; set; }

        [global::Bond.Id(2)]
        public EnumItemType type { get; set; }

        [global::Bond.Id(3)]
        public List<int> attrs { get; set; }

        [global::Bond.Id(4)]
        public long end { get; set; }

        public DataItem()
            : this("Game.Models.DataItem", "DataItem")
        {}

        protected DataItem(string fullName, string name)
        {
            title = "";
            type = EnumItemType.TypeNone;
            attrs = new List<int>();
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.0")]
    public partial class DataGrainState
    {
        [global::Bond.Id(0)]
        public List<DataItem> item1s { get; set; }

        [global::Bond.Id(1)]
        public Dictionary<int, DataItem> item2s { get; set; }

        [global::Bond.Id(2)]
        public List<int> attrs { get; set; }

        public DataGrainState()
            : this("Game.Models.DataGrainState", "DataGrainState")
        {}

        protected DataGrainState(string fullName, string name)
        {
            item1s = new List<DataItem>();
            item2s = new Dictionary<int, DataItem>();
            attrs = new List<int>();
        }
    }
} // Game.Models
