
//------------------------------------------------------------------------------
// This code was generated by a tool.
//
//   Tool : Bond Compiler 0.11.0.0
//   Input filename:  C:\Item\youigame\trunk\tools\DtsGenerator\bond\message.bond
//   Output filename: message_types.cs
//
// Changes to this file may cause incorrect behavior and will be lost when
// the code is regenerated.
// <auto-generated />
//------------------------------------------------------------------------------


// suppress "Missing XML comment for publicly visible type or member"
#pragma warning disable 1591


#region ReSharper warnings
// ReSharper disable PartialTypeWithSinglePart
// ReSharper disable RedundantNameQualifier
// ReSharper disable InconsistentNaming
// ReSharper disable CheckNamespace
// ReSharper disable UnusedParameter.Local
// ReSharper disable RedundantUsingDirective
#endregion

namespace Game.Models
{
    using System.Collections.Generic;

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.0")]
    public partial class Message
    {
        [global::Bond.Id(0)]
        public EnumItemType ret { get; set; }

        public Message()
            : this("Game.Models.Message", "Message")
        {}

        protected Message(string fullName, string name)
        {
            ret = EnumItemType.TypeNone;
        }
    }

    [global::Bond.Schema]
    [System.CodeDom.Compiler.GeneratedCode("gbc", "0.11.0.0")]
    public partial class MsgTest
        : Message
    {
        [global::Bond.Id(0)]
        public DataItem item { get; set; }

        public MsgTest()
            : this("Game.Models.MsgTest", "MsgTest")
        {}

        protected MsgTest(string fullName, string name)
        {
            item = new DataItem();
        }
    }
} // Game.Models
